name: "ui-test"
on:
  push:
    branches: ["dev", "main"]
  pull_request_target:
    branches: ["dev", "main"]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      AZURE_TENANT_NAME: microsoft
      AZURE_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
      AZURE_SUBSCRIPTION_NAME: 'Teams Cloud - E2E Testing with TTL = 1 Days'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Setup project
        run: |
          npm install
          npm run package
      - name: setup account
        uses: jsdaniell/create-json@v1
        with:
          name: "config.json"
          json: ${{ secrets.ACCOUNT_CONFIG }}
          dir: "./src/test/e2e"
      - run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npx playwright test
        working-directory: ./src/test/e2e
      - if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            test-results
